# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-05 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Category', verbose_name='分类'),
            preserve_default=False,
        ),
    ]
