# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, '发布'), (2, '删除')], default=1, verbose_name='状态'),
        ),
    ]
