# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-05 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='api.Tag', verbose_name='标签'),
        ),
    ]
