# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-07 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '咨询'), (2, '公司动态'), (3, '分享'), (4, '答疑'), (5, '其他')], verbose_name='分类')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('image', models.CharField(max_length=128, verbose_name='图片路径')),
                ('summary', models.CharField(max_length=255, verbose_name='简介')),
            ],
        ),
    ]
