# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-08 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(max_length=64, null=True, verbose_name='登录认证码'),
        ),
    ]
